name: CI

"on":
  pull_request:

jobs:
  tex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Get SHA
        id: short-sha
        run: |
          echo "::set-output name=sha::$(echo ${{'{{'}} github.event.pull_request.head.sha {{'}}'}} | cut -c 1-7)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: token
          password: ${{'{{'}} secrets.GITHUB_TOKEN {{'}}'}}

      - name: TeX build
        run: |
          docker run -v `pwd`:/workspace -w /workspace ghcr.io/spherex/spherex-tex:latest sh -c 'make'

      - name: Rename PDF
        run: mv {{ cookiecutter.handle }}.pdf {{ cookiecutter.handle }}-${{'{{'}} steps.short-sha.outputs.sha {{'}}'}}.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: {{ cookiecutter.handle }}-${{'{{'}} steps.short-sha.outputs.sha {{'}}'}}.pdf
          path: {{ cookiecutter.handle }}-${{'{{'}} steps.short-sha.outputs.sha {{'}}'}}.pdf
          retention-days: 14
